create table IF NOT EXISTS USERS (
    ID              bigint generated by default as identity,
    USERNAME        varchar(255),
    PASSWORD        varchar(255)

);


insert into USERS(ID, USERNAME, PASSWORD) values (1,'admin','dc80cd536dbc129e1bd12d76dfbe0d994bbd18c8a0445e4f');